### ISSUE TITLE
Create DB

### ISSUE THREAD

**Issue by zmwebdev** [zmwebdev/php-todo-app#11]
(lists)-1-<>-n-(tasks)

**Comment by Izayer** [comment]
Nere datu basea:

Usuario N< usuarios_listas>M Listas 1<>N tareas

CREATE TABLE usuarios ( 
ID int(8) unsigned NOT NULL auto_increment, 
username varchar(20) NOT NULL, 
password varchar(25) NOT NULL, 
nombre varchar(30) NOT NULL, 
apellidos varchar(30) NOT NULL, 
telefono varchar(30), 
email varchar(40) NOT NULL, 
PRIMARY KEY (ID) 
); 

CREATE TABLE listas (
ID int(8) unsigned NOT NULL auto_increment,
nombre varchar(25) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE usuarios_listas
(
ID int(8) unsigned NOT NULL auto_increment,
ID_usuarios int(8) unsigned NOT NULL,
ID_listas int(8) unsigned NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID_usuarios) REFERENCES todo.usuarios(ID) ,
FOREIGN KEY (ID_listas) REFERENCES todo.listas(ID)
);

CREATE TABLE tareas (
ID int(8) unsigned NOT NULL auto_increment,
nombre varchar(30) NOT NULL,
descripcion varchar(100) NOT NULL,
hecho BOOLEAN DEFAULT FALSE, 
ID_listas int(8) unsigned NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID_listas) REFERENCES todo.listas(ID)
);
